# Generated by Django 3.0.4 on 2020-03-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_auto_20200308_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_uploader',
            old_name='image',
            new_name='file',
        ),
    ]
