# Generated by Django 3.0.4 on 2020-03-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_auto_20200319_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flower',
        ),
    ]
